import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/footer";
import { icons } from "lucide-react";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

const img =  <Image
        src="/logo.png" // Path to your image
        alt="Logo"
        className="absolute rounded-full" // Position the image inside the SVG container
      />

export const metadata = {
  title: "Deep Blogs",
  description: "Generated by create next app",
  icons: "/logo2.png"
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-p-20 scroll-smooth" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        {children}
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}